/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseButtonIcon: typeof import('./src/components/BaseButtonIcon.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardPaginations: typeof import('./src/components/CardPaginations.vue')['default']
    CollapseTransition: typeof import('./src/components/CollapseTransition.vue')['default']
    ConfirmationModal: typeof import('./src/components/ConfirmationModal.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownAnimation: typeof import('./src/components/DropdownAnimation.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./src/components/DropdownMenu.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FormSelect: typeof import('./src/components/FormSelect.vue')['default']
    FormTextarea: typeof import('./src/components/FormTextarea.vue')['default']
    HelpTooltip: typeof import('./src/components/HelpTooltip.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    ImageLightbox: typeof import('./src/components/ImageLightbox.vue')['default']
    InfoItem: typeof import('./src/components/InfoItem.vue')['default']
    LoadingSVG: typeof import('./src/components/LoadingSVG.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ResultCount: typeof import('./src/components/Table/ResultCount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableSelect: typeof import('./src/components/SearchableSelect.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/Sidebar/SidebarItem.vue')['default']
    SidebarList: typeof import('./src/components/Sidebar/SidebarList.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    SnackBar: typeof import('./src/components/Snack/SnackBar.vue')['default']
    SnackBarItem: typeof import('./src/components/Snack/SnackBarItem.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    SwitchInput: typeof import('./src/components/SwitchInput.vue')['default']
    TableHeader: typeof import('./src/components/TableHeader.vue')['default']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    TableSkeleton: typeof import('./src/components/Skeletons/TableSkeleton.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
    UserAvatars: typeof import('./src/components/UserAvatars.vue')['default']
    UserProfileDropdown: typeof import('./src/components/navbar/UserProfileDropdown.vue')['default']
    ViewHeader: typeof import('./src/components/ViewHeader.vue')['default']
    WarningAlert: typeof import('./src/components/WarningAlert.vue')['default']
  }
}
